"""add_trade_no_string

Revision ID: 701493f5e564
Revises: 3c908c88aee1
Create Date: 2020-04-30 17:14:52.229571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701493f5e564'
down_revision = '3c908c88aee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_order_info', sa.Column('trade_no', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_order_info', 'trade_no')
    # ### end Alembic commands ###
