"""add_trade_no2

Revision ID: fb16ea1bad64
Revises: 7e2e83388e2a
Create Date: 2020-04-30 15:29:12.537319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb16ea1bad64'
down_revision = '7e2e83388e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ih_order_info', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ih_order_info', sa.Column('comment', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
